# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8985be994f3550ab1c7079485767417f6b0997d2324cf66a5af5fb94e466a11cef5049b7cb94fc4af505b26500aa149072ac225176b69bca61246901e6ad5175

test:
  secret_key_base: 1539ed51514d807ec2ba41dcf5a58da2cc44eed520fca793019b71ad372406ceaf7649df27ffce7219d80b4458fbe9f37991044034055264fb1a6649be1cbe9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
